#!/bin/sh

# TMP Files
FILE1=/tmp/translate1-$$
FILE2=/tmp/translate2-$$

# Network Info
HOST=localhost
PORT=1235

# Gettext cmd
GETTEXT="gettext -d translate_ui"

# Stops application
end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

# Prints hint how to call usage
hintUsage () {
	echo See usage with --help.
	exit -1
}

# Prints usage
printUsage () {
	echo "Usage: $0 [ --network [host [port]] | --help ]" 
	exit -1
}


# Handle parameters
if [ $# -eq 0 ]
then
	TRANSLATE=translate
elif [ $# -ge 1 ]
then
	if [ $1 = '--help' ]
	then
		printUsage
	elif [ $1 = '--network' ]
	then
		if [ $# -ge 2 ]
		then 
			HOST=$2
		elif [ $# -ge 3 ]
		then
			PORT=$3
		fi
		TRANSLATE="nc $HOST $PORT"
	else
		hintUsage
	fi
else
	hintUsage
fi

# Setup UI
which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

# Run UI
while true
do
	$DIALOG --inputbox "`curl -s --fail --show-error http://semes-olla.rhcloud.com/words?Swadesh/English.py | sed -n '/^$/!{s/<[^>]*>//g;p;}' | paste - - - - - - - -`\\n\\n`$GETTEXT \"Enter Number:\"`" 0 0 2> $FILE1 || end
	cat $FILE1 | $TRANSLATE > $FILE2

	if [ -s "$FILE2" ]
	then
		MSG="`$GETTEXT \"Translation:\"` `cat $FILE2`.\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 0 0 || end
	else
		MSG="`$GETTEXT \"Error.\"`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 0 0 || end
	fi
done

