#!/bin/sh

FILE1=/tmp/translate1-$$
FILE2=/tmp/translate2-$$
ERROR=/tmp/translate-err-$$

HOST=localhost
PORT=1235
MODE=local

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

hintUsage () {
	echo See usage with --help.
	exit -1
}

printUsage () {
	echo "Usage: $0 [ --network [host [port]] | --help ]" 
	exit -1
}



# Handle parameters
if [ $# -eq 0 ]
then
	MODE=local
elif [ $# -ge 1 ]
then
	if [ $1 = '--help' ]
	then
		printUsage
	elif [ $1 = '--network' ]
	then
		MODE=network
		if [ $# -ge 2 ]
		then 
			HOST=$2
		elif [ $# -ge 3 ]
		then
			PORT=$3
		fi
	else
		hintUsage
	fi
else
	hintUsage
fi

which gdialog 2> /dev/null && DIALOG=dialog || DIALOG=dialog

while true
do
	#`curl http://semes-olla.rhcloud.com/words?Swadesh/English.py`
	$DIALOG --inputbox "Enter Number" 0 0 2> $FILE1 || end
	INPUT=`cat $FILE1`

	if [ $MODE = 'local' ]
	then
		curl -s "http://semes-olla.rhcloud.com/word?$INPUT&Swadesh/Germanic/German.py" > $FILE2
	else
		TRANSLATE="nc $HOST $PORT"
		echo $INPUT | $TRANSLATE > $FILE2 2> $ERROR
	fi

	if [ -s "$FILE2" ]
	then
		MSG="Translation: `cat $FILE2`. Continue?"
		$DIALOG --yesno "$MSG" 0 0 || end
	else
		MSG="Error. Continue?"
		$DIALOG --yesno "$MSG" 0 0 || end
	fi
done

