#!/bin/sh

FILE1=/tmp/translate1-$$
FILE2=/tmp/translate2-$$
ERROR=/tmp/translate-err-$$

HOST=localhost
PORT=1235

TRANSLATE=translate
GETTEXT="gettext -d calc_ui"

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

hintUsage () {
	echo See usage with --help.
	exit -1
}

printUsage () {
	echo "Usage: $0 [ --network [host [port]] | --help ]" 
	exit -1
}



# Handle parameters
if [ $# -eq 0 ]
then
	MODE=local
elif [ $# -ge 1 ]
then
	if [ $1 = '--help' ]
	then
		printUsage
	elif [ $1 = '--network' ]
	then
		TRANSLATE="nc $HOST $PORT"
		if [ $# -ge 2 ]
		then 
			HOST=$2
		elif [ $# -ge 3 ]
		then
			PORT=$3
		fi
	else
		hintUsage
	fi
else
	hintUsage
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

while true
do
	#`curl http://semes-olla.rhcloud.com/words?Swadesh/English.py`
	$DIALOG --inputbox "`$GETTEXT \"Enter Number:\"`" 0 0 2> $FILE1 || end

	if cat $FILE1 | $TRANSLATE > $FILE2 2> $ERROR

	#if [ -s "$FILE2" ]
	then
		MSG="`$GETTEXT \"Translation:\"` `cat $FILE2`.\\n\\nContinue?"
		$DIALOG --yesno "$MSG" 0 0 || end
	else
		MSG="`$GETTEXT \"Error.\\n\\nContinue?\"`"
		$DIALOG --yesno "$MSG" 0 0 || end
	fi
done

